### ISSUE TITLE
Roadmap - Introduce New Features to Improve Usability

### ISSUE THREAD

**Issue by davidpickering** [midohiofoodbank/freshtrak-pantry-finder-api#13]
Customer Story: I am a customer using FreshTrak.com to find food resources. I would like to have more options on the site to sort and filter results to better suit my needs.
- I need food today and only want to see results for today. -or - I need food, but I only have transportation available six days from now. Please only show me options for that specific day. (optimize for time)
- I do not have reliable transportation and have to walk to locate food resources. I only want to see options within 1 mile of my current location. (optimize for distance)
- I am looking for a specific type of service, please only show me results for [service category] (optimize for service provided)

### Add Distance to improve usability of results: 
The main improvement to the results can come from simply sorting results in a date by distance short-long. There are a few variations of this idea, but here is the general progression on the API's side.
#11 - Add distance to Agency response

#9 -  Add zip_code centroid distance to event response

#10 -  Add user's location distance to Event response

### Add information to control future features and customize feedback to the customer.
#16 - Add interest, reservations, walkins to the agencies JSON response

### - Exception Note: This feature helps add functionality and answers when an agency's service area is not perfectly described by a zip code.
#18 - Add Exception Note to Agencies API Response

### Customer Note
One of the early pieces of feedback we have received from testing is that we need a mechanism to feed additional information and/or instructions to customers using the site. This concept is captured in the wireframes, and detailed in the following issue:
#15 - Add Additional information to Agencies API Response

**Comment by PhilNorman2** [comment]
>I need food today and only want to see results for today. -or - I need food, but I only have transportation available six days from now. Please only show me options for that specific day. (optimize for time)

Some of this is already available.  If you input an event_date in the future it will only show events from that date onwards.

**Comment by davidpickering** [comment]
Closed in favor of Asana Project Management strategy
