### ISSUE TITLE
Add interest, reservations, walkins to the agencies JSON response

### ISSUE THREAD

**Issue by davidpickering** [midohiofoodbank/freshtrak-pantry-finder-api#16]
Date is in the event_dates table:

- accepts_walkins
- accepts_reservations
- accepts_interest

![image](https://user-images.githubusercontent.com/11682225/81412790-63525380-9112-11ea-86fc-e667c1f2105a.png)

**Comment by PhilNorman2** [comment]
Here is an example response that concurs with what is in the event_dates table:

<pre>
 "event_dates": [
                        {
                            "id": 4,
                            "event_id": 822,
                            "capacity": 100,
                            "accept_walkin": 1,
                            "accept_reservations": 0,
                            "accept_interest": 1,
                            "start_time": "8:30 AM",
                            "end_time": "11:30 AM",
                            "date": "2020-05-20"
                        },
</pre>

**Comment by davidpickering** [comment]
Wohoo! Looks great! Exactly what I would expect. 

I checked event_date #4 in the DB, and can confirm that is the data I see.

**Comment by davidpickering** [comment]
Hey Phil. How close did this one get to being a PR? I know you had exception note as a PR already, but there were some potential revision. Foodbank-priority would be this feature over a revised exception note PR.

**Comment by PhilNorman2** [comment]
Good to know.  I was going to include #16 with #15. I already have an
initial commit but  #15 depends on PR #20.
