### ISSUE TITLE
Add Exception Note to Agencies API Response

### ISSUE THREAD

**Issue by davidpickering** [midohiofoodbank/freshtrak-pantry-finder-api#18]
Agency Story: I run an agency and have a service area that does not perfectly match a set of zip codes. I want to include all the possible zip codes that cover my service territory, and then for select ones let customers know that they "Must be a resident of the ABC School District".

Example: [Mid-Ohio Market at Heart](https://www.heart-market.org/)

![image](https://user-images.githubusercontent.com/11682225/81424163-876a6080-9123-11ea-9f67-9af25653f288.png)

Their service territory can be described in terms of zip codes and returned as a possibility for residents of those zip codes, but there are exceptions to who they will serve:

![image](https://user-images.githubusercontent.com/11682225/81429785-517daa00-912c-11ea-8d8c-10ff28b98aae.png)

Data:
- event_service_geographies.trigger_exception_note == 1 - show the exception note from event_geography_profiles.exception_note.
- event_service_geographies.trigger_exception_note == 0 - do not show the exception note
- event_geography_profiles.exception_note - e.g. "Rolling Hills School District"
- these data structures are connected through the egp_id fields.
- Data should be returned as a property of the event in the agencies API response.

To-Do Items:
- add a new model for event_geography_profiles
- In the [event_zip_code.rb model](https://github.com/midohiofoodbank/freshtrak-pantry-finder-api/blob/master/app/models/event_zip_code.rb), add a belongs to event_geography_profiles using foreign key egp_id.
- Add the exception note into the agencies API response as a property of the event.

**Comment by PhilNorman2** [comment]
I am starting to get results from the API.

Logic:  

First a query to get all possible EGP records that match criteria (duplicates on event_id included)

exception_notes  = EventGeography.joins(:event_zip_codes).where(event_service_geographies: { trigger_exception_note: 1 }).to_sql
=> "SELECT `event_geography_profiles`.* FROM `event_geography_profiles` INNER JOIN `event_service_geographies` ON `event_service_geographies`.`geo_type_id` = 1 AND `event_service_geographies`.`status_id` = 1 AND `event_service_geographies`.`egp_id` = `event_geography_profiles`.`egp_id` WHERE `event_geography_profiles`.`status_id` = 1 AND `event_service_geographies`.`trigger_exception_note` = 1"

Then I convert that to a hash which de-duplicates event_ids

irb(main):073:0> y_ids_hash = y.map{ |c| [c.exception_note,c.event_id] }.to_h
=> {"Monroe Co., Riverfront"=>617, "Delivery - Lancaster Only, Office Visits - Fairfield County Residents"=>667, "Coshocton/Knox"=>788, "serving Franklin County"=>5278, "W Franklin"=>1370, "veterans"=>1080, "Serving Zip Codes 43123, 43126, 43146"=>188, "West of Central"=>1487, "Bellaire;Martins Ferry;Moundsville;Wheeling;Denwood  Town/City"=>528, "Madison County"=>308, "London  Town/City"=>1947, "Residents Only"=>988, "Canal Winchester, Lithopolis, Carroll"=>303, "Westerville School District"=>1382, "Hilliard School District"=>3558, "residents only"=>1266, "Pleasantville"=>5598, "Hilliard/Dublin School District"=>1479, "Bloom Carroll School District"=>3782, "Pickerington School District"=>1804, "Reynoldsburg City limits to I-70 on south,Hamilton Rd. on North, adding 43068"=>3546, "Scio, Jewett, and Bowerston    "=>670, "Walnut Twp and surrounding area Town/City"=>159, "Licking, Fairfield, Franklin"=>583, "Reynoldsburg School District"=>1239, "Plain Local School District"=>2729, "Dublin School District"=>743}

The hash gets sent to the event_serializer where the excepton_note is looked up by the event_id (hash.key)

In this case, the event_id is 159

irb(main):082:0> exception_notes_hash.key(159)
=> "Walnut Twp and surrounding area Town/City"

**Comment by PhilNorman2** [comment]
Here is an example API request/response:

http://localhost:8888/api/agencies?zip_code=43148

<pre>
{
    "agencies": [
        {
            "id": 104,
            "address": "2315 WEEKLY AVE",
            "city": "MILLERSPORT",
            "state": "OH",
            "zip": "43046",
            "phone": "614-314-3901",
            "name": "Millersport Community Food Pantry",
            "nickname": "Millersport Community Food Pantry",
            "estimated_distance": 5.67,
            "events": [
                {
                    "id": 159,
                    "address": "2315 WEEKLY AVE ",
                    "city": "MILLERSPORT",
                    "state": "OH",
                    "zip": "43046",
                    "agency_id": 104,
                    "latitude": "39.90037882",
                    "longitude": "-82.53778996",
                    "name": "Pantry",
                    "service": "Choice Pantry",
                    "estimated_distance": 5.67,
                    "exception_note": "Walnut Twp and surrounding area Town/City",
                    "event_dates": [
                        {
                            "id": 108,
                            "event_id": 159,
                            "capacity": 100,
                            "start_time": "7 PM",
                            "end_time": "8:30 PM",
                            "date": "2020-05-14"
                        },
                        {
                            "id": 109,
                            "event_id": 159,
                            "capacity": 100,
                            "start_time": "7 PM",
                            "end_time": "8:30 PM",
                            "date": "2020-05-21"
                        },
                        {
                            "id": 110,
                            "event_id": 159,
                            "capacity": 100,
                            "start_time": "7 PM",
                            "end_time": "8:30 PM",
                            "date": "2020-05-28"
                        }
                    ]
                }
            ]
        },
        {
            "id": 332,
            "address": "112 LINCOLN AVE ",
            "city": "PLEASANTVILLE",
            "state": "OH",
            "zip": "43148",
            "phone": "740-468-3257",
            "name": "Outreach Mission Pantry",
            "nickname": "Outreach Mission Pantry",
            "estimated_distance": 1.2,
            "events": [
                {
                    "id": 5598,
                    "address": "112 LINCOLN AVE  ",
                    "city": "PLEASANTVILLE",
                    "state": "OH",
                    "zip": "43148",
                    "agency_id": 332,
                    "latitude": "39.8083177",
                    "longitude": "-82.5214868",
                    "name": "Drive Thru",
                    "service": "Prepack Pantry",
                    "estimated_distance": 1.2,
                    "exception_note": "Pleasantville",
                    "event_dates": []
                }
            ]
        }
    ]
}
</pre>

**Comment by PhilNorman2** [comment]
@davidpickering Any ideas on acceptance testing?   BTW, The count in my criteria query is 336.  The current count on AWS RDS freshtrak public is 406.  I am guessing you have been adding more exception notes.

**Comment by davidpickering** [comment]
> => "SELECT event_geography_profiles.* FROM event_geography_profiles INNER JOIN event_service_geographies ON event_service_geographies.geo_type_id = 1 AND event_service_geographies.status_id = 1 AND event_service_geographies.egp_id = event_geography_profiles.egp_id WHERE event_geography_profiles.status_id = 1 AND event_service_geographies.trigger_exception_note = 1"

Yep, Query looks good, right scopes on everything

> Then I convert that to a hash which de-duplicates event_ids

Didn't know you could do that! Great!

![image](https://user-images.githubusercontent.com/11682225/81710561-cf99c380-9440-11ea-9053-df8bf9cbd59e.png)

JSON looks good!

The data also passes my smell test. I recognize those two agencies as having exception notes.

Acceptance testing: (based on data currently in FreshTrak Public)
- zip code 43148, on 5/16 - should see a result for Outreach Mission Pantry, with an exception note of "Pleasantville Township Residents Only"
- zip code 43147, on 5/12 (or 5/19) - should see a result for Homeless Families Foundation, with an exception note of "Serving Franklin County"

You should continue to see that count on AWS RDS go up. We are releasing more schedule data daily.

**Comment by PhilNorman2** [comment]
I went ahead and refreshed my database so I could verify the ACTs.  Results are snippets showing agencies/events relative to expected results.  

> zip code 43148, on 5/16 - should see a result for Outreach Mission Pantry, with an exception note of "Pleasantville Township Residents Only"

request: http://localhost:8888/api/agencies?zip_code=43148&event_date=05-12-2020

response:
<pre>
{
            "id": 332,
            "address": "112 LINCOLN AVE ",
            "city": "PLEASANTVILLE",
            "state": "OH",
            "zip": "43148",
            "phone": "740-468-3257",
            "name": "Outreach Mission Pantry",
            "nickname": "Outreach Mission Pantry",
            "events": [
                {
                    "id": 5598,
                    "address": "112 LINCOLN AVE   ",
                    "city": "PLEASANTVILLE",
                    "state": "OH",
                    "zip": "43148",
                    "agency_id": 332,
                    "latitude": "39.8083177",
                    "longitude": "-82.5214868",
                    "name": "Drive Thru",
                    "service": "Prepack Pantry",
                    "exception_note": "Pleasantville Township Residents Only",
                    "event_dates": [
                        {
                            "id": 623,
                            "event_id": 5598,
                            "start_time": "09:00 AM",
                            "end_time": "11:00 AM",
                            "date": "2020-05-16"
                        }
                    ]
                }
            ]
        }
</pre>

The query above also resulted in an exception note for" Millersport Community Food Pantry" that reads "Walnut Twp and surrounding area Town/City".

>zip code 43147, on 5/12 (or 5/19) - should see a result for Homeless Families Foundation, with an exception note of "Serving Franklin County"

request: http://localhost:8888/api/agencies?zip_code=43147&event_date=05-12-2020

response:
<pre>
 {
            "id": 3303,
            "address": "33 N GRUBB ST",
            "city": "COLUMBUS",
            "state": "OH",
            "zip": "43215",
            "phone": "614-325-0045",
            "name": "Homeless Families Foundation",
            "nickname": "Homeless Families Foundation",
            "events": [
                {
                    "id": 5278,
                    "address": "33 N GRUBB ST  ",
                    "city": "COLUMBUS",
                    "state": "OH",
                    "zip": "43215",
                    "agency_id": 3303,
                    "latitude": "39.9610804",
                    "longitude": "-83.0180218",
                    "name": "Pantry",
                    "service": "Choice Pantry",
                    "exception_note": "serving Franklin County",
                    "event_dates": [
                        {
                            "id": 1891,
                            "event_id": 5278,
                            "start_time": "10:00 AM",
                            "end_time": "04:00 PM",
                            "date": "2020-05-12"
                        },
                        {
                            "id": 1892,
                            "event_id": 5278,
                            "start_time": "10:00 AM",
                            "end_time": "04:00 PM",
                            "date": "2020-05-19"
                        },
</pre>

**Comment by PhilNorman2** [comment]
Here is that additional exception note from the first query:

http://localhost:8888/api/agencies?zip_code=43148&event_date=05-12-2020

<pre>
"events": [
                {
                    "id": 159,
                    "address": "2315 WEEKLY AVE  ",
                    "city": "MILLERSPORT",
                    "state": "OH",
                    "zip": "43046",
                    "agency_id": 104,
                    "latitude": "39.90037882",
                    "longitude": "-82.53778996",
                    "name": "Pantry",
                    "service": "Choice Pantry",
                    "exception_note": "Walnut Twp and surrounding area Town/City",
                    "event_dates": [
                        {
                            "id": 108,
                            "event_id": 159,
                            "start_time": "07:00 PM",
                            "end_time": "08:30 PM",
                            "date": "2020-05-14"
                        },
                        {
                            "id": 109,
                            "event_id": 159,
                            "start_time": "07:00 PM",
                            "end_time": "08:30 PM",
                            "date": "2020-05-21"
                        },
</pre>

**Comment by PhilNorman2** [comment]
Also, you won't see estimated_distance here because I now have this code on another branch off of master.
