### ISSUE TITLE
Scopes for Published End Date & Time

### ISSUE THREAD

**Issue by PhilNorman2** [midohiofoodbank/freshtrak-pantry-finder-api#31]
Idea is to stop publishing an entry when it is no longer useful to the customers
Fields in freshtrak_public.event_dates
Published_end_date_key - defaults to same day as the event_date
Published_end_time_key - defaults to 1 hour before the end of the distribution
Build new scopes like:

TD - Make two named scopes
TD - Apply the two new named scopes to the default scope
Main Use: Stops publishing entries today ~ 1 hour before they end (logic handled by PantryTrak Admin code)
Additional use: Let’s sites customize the date/time they want to stop taking reservations - e.g.”We need at least 48 hours advance notice to pre-pack and begin shipping boxes to the site”

Example: At 2PM, only the "Community Blessing" would be showing.
![image](https://user-images.githubusercontent.com/11682225/83934126-55790800-a77c-11ea-910b-652e2bc6bb5a.png)

**Comment by PhilNorman2** [comment]
I realized that I cannot use the published_end_time_key alone for a scope.  Otherwise no event_dates in the future past the published_end_time_key will be shown, e.g., no event_dates will show at the end of the day.

I think the published_end_time_key needs to be tied to the published_end_date_key.  The logic would be something like this.

where(current_date:current_time <= published_end_date_key:published_end_time_key)

If this makes sense will this scope suffice for both cases?  Typically a date:time is converted to an integer for comparison purposes.

**Comment by PhilNorman2** [comment]
Unfortunately I cannot do a query on a virtual column so we will need a new column, e.g., published_datetime_end_key, in the database.  It needs to be stored as an integer, the number of seconds since 1st Jan 1970 00.00 AM, which is a common way to store dates in a database.  Then I can do a query to compare it against the current DateTime (in seconds).  Example in Ruby:

irb(main):002:0> DateTime.now
=> Mon, 08 Jun 2020 15:32:15 -0400
irb(main):003:0> DateTime.now.to_i
=> 1591644746

**Comment by davidpickering** [comment]
@PhilNorman2 We have accomplished the published_end_datetime conversion. Business rules is that it defaults to 1 hour before the posted end time of the event date, but is written in UTC. 
E.g. A distribution is on 07/08/2020 and lasts from 4PM (1600) to 6PM (1800). It should stop being published at 5PM on 7/8/2020. Standardized to UTC, it would stop being published at 9PM on 7/8/2020 (2020-07-08 21:00:00 UTC) . This is now reflected in all of the event_dates and can be fully tested.

Thanks @thompson2091 for the assist
