### ISSUE TITLE
Pantry-Finder / Results for a Single Agency

### ISSUE THREAD

**Issue by davidpickering** [midohiofoodbank/freshtrak-pantry-finder-api#32]
Want a way to get the agencies API results, just for a single agency.:
- E.g. - An agency wants to provide a link to “All of our upcoming distributions”
- Admin UI would make the link for the user, just need a path on FreshTrak to filter down the agencies results to a single agency for a single zip code.
- Approach
- Accept locations.loc_id (agency.id) -or- events.event_id (events.id)
- Add a show method to the agency controller (handles the locations.loc_id (agency.id) example)
- E.g. https://beta.freshtrak.com/events/list/6

Example Mock up:

![image](https://user-images.githubusercontent.com/11682225/83934165-9b35d080-a77c-11ea-9af2-615053be67d3.png)

**Comment by PhilNorman2** [comment]
I added the show method for the agencies API.  I found I could use the agencies zip to display the exception_note.  @davidpickering  do you think that makes sense?  I think I could also show the estimated_distance from the center of the agencies zip if we wanted to do that. Below is an example with an exception_note displayed (agency zip == 43215)

http://localhost:8888/api/agencies/3303

<pre>
{
    "agency": {
        "id": 3303,
        "address": "33 N GRUBB ST",
        "city": "COLUMBUS",
        "state": "OH",
        "zip": "43215",
        "phone": "614-325-0045",
        "name": "Homeless Families Foundation",
        "nickname": "Homeless Families Foundation",
        "estimated_distance": "",
        "events": [
            {
                "id": 5278,
                "address": "33 N GRUBB ST  ",
                "city": "COLUMBUS",
                "state": "OH",
                "zip": "43215",
                "agency_id": 3303,
                "latitude": "39.9610804",
                "longitude": "-83.0180218",
                "name": "Pantry",
                "service": "Choice Pantry",
                "estimated_distance": "",
                "exception_note": "serving Franklin County",
                "event_details": "",
                "agency_name": "Homeless Families Foundation",
                "event_dates": [
                    {
                        "id": 1895,
                        "event_id": 5278,
                        "capacity": 100,
                        "accept_walkin": 1,
                        "accept_reservations": 0,
                        "accept_interest": 1,
                        "start_time": "10 AM",
                        "end_time": "4 PM",
                        "date": "2020-06-09"
                    },
                    {
                        "id": 1896,
                        "event_id": 5278,
                        "capacity": 100,
                        "accept_walkin": 1,
                        "accept_reservations": 0,
                        "accept_interest": 1,
                        "start_time": "10 AM",
                        "end_time": "4 PM",
                        "date": "2020-06-16"
                    },
                    {
                        "id": 1897,
                        "event_id": 5278,
                        "capacity": 100,
                        "accept_walkin": 1,
                        "accept_reservations": 0,
                        "accept_interest": 1,
                        "start_time": "10 AM",
                        "end_time": "4 PM",
                        "date": "2020-06-23"
                    },
                    {
                        "id": 1898,
                        "event_id": 5278,
                        "capacity": 100,
                        "accept_walkin": 1,
                        "accept_reservations": 0,
                        "accept_interest": 1,
                        "start_time": "10 AM",
                        "end_time": "4 PM",
                        "date": "2020-06-30"
                    }
                ]
            }
        ]
    }
}
</pre>

**Comment by davidpickering** [comment]
@PhilNorman2 
> I found I could use the agencies zip to display the exception_note. @davidpickering do you think that makes sense?

Short answer; Yes I think that makes sense and it is a common sense way to tackle this question.

Long Answer:
- Overall I think that makes sense and it is the right way to tackle the problem
- These requests for "View our entire schedule" are un-specific and we cannot arbitrarily limit results, or provide enhanced feedback without more information. Defaulting to exception notes in the agency's zip code gives us the best chance at getting this right.
- The super duper right way to answer this question would be: 1. a link to this page, 2. The request gets intercepted and asks "do you live in one of the following zip codes", 3. If they do, we show them the results for their zip code, if they do not then we say "we do not think you are eligible to attend this agency" and give them an option to go home/see it anyway.
