### ISSUE TITLE
enhancement: fetch event slots by event_date_id

### ISSUE THREAD

**Issue by maheshkurma** [midohiofoodbank/freshtrak-pantry-finder-api#33]
Fetch event slots by event_date_id

Add Serializers - EventHourSerializer, EventSlotSerializer

Add new API Calls - EventHoursController
- GET /api/event_hours
- GET /api/event_dates/:id/event_hours
- GET /api/event_hours/:id

**Comment by davidpickering** [comment]
Closed by PR #34
