### ISSUE TITLE
Foodbank Card - HTML Text for Foodbank 

### ISSUE THREAD

**Issue by davidpickering** [midohiofoodbank/freshtrak-pantry-finder-api#36]
Foodbank Card - HTML Text for Foodbank - each foodbank can set up their own eligiblity requirements - solves a regulatory/compliance issue.

![image](https://user-images.githubusercontent.com/11682225/85319846-2c50bb00-b490-11ea-8906-3b16791a6194.png)

Requirements:
- Add the fb_html field to the foodbanks JSON response

**Comment by PhilNorman2** [comment]
Looks like all of the values for fb_html in foodbanks_mini are null.  

select fb_html from foodbanks_mini where fb_html is not null
returns 0 records.

From what I have read ActiveRecord will interpret a blob as a string.  It would be nice to an example loaded.  I can look into updating a local record with some simple html (but I think our environments may have that disabled).

**Comment by PhilNorman2** [comment]
If these are html pages have you considered storing them as files?  Then all that is stored in the db is a URL.  This would also allow you to easily spot check them if support issues come up.

**Comment by davidpickering** [comment]
The idea about html pages is not bad, but I'm not sure we're ready to support that amount of lift to get the feature off the ground. We are not planning on a lot of complexity or graphics, so storing in the DB seems like the right amount of control we are looking for. 

I am temporarily away from my main working location and having VPN issues. When I get this fixed I'll get some test data into those fields.

**Comment by davidpickering** [comment]
Closed pending more specific use case from foodbank partners
