### ISSUE TITLE
Dynamic age controls

### ISSUE THREAD

**Issue by PhilNorman2** [midohiofoodbank/freshtrak-pantry-finder-api#39]
![image](https://user-images.githubusercontent.com/31697968/85869932-5fe65a80-b79a-11ea-83c4-32d7f132aada.png)

**Comment by davidpickering** [comment]
SQL to mirror with Model: SELECT
	forms.form_id, 
	forms.form_num, 
	forms.form_master_num, 
	forms.form_name, 
	forms.effective_start, 
	forms.effective_end, 
	forms.`language`, 
	forms.language_id
FROM
	forms
WHERE
	forms.form_master_num = 'oh_jfs_04221' 
	AND '2020-06-26' BETWEEN forms.effective_start AND forms.effective_end
	AND language_id = 1
	 
Already shared with Phil
