### ISSUE TITLE
remove service attribute from the event object.

### ISSUE THREAD

**Issue by maheshkurma** [midohiofoodbank/freshtrak-pantry-finder-api#52]
Remove service attribute from the event object.
Issue: It returns same value multiple times in service & service_category_name, can see in below image. 

<img width="546" alt="Screen Shot 2020-08-18 at 10 38 50 AM" src="https://user-images.githubusercontent.com/20909776/90527022-12a1bc00-e13f-11ea-8b1a-1119eb888740.png">

**Comment by davidpickering** [comment]
Confirmed this in Beta. Good work everyone! 
![image](https://user-images.githubusercontent.com/11682225/90690231-554abd80-e23f-11ea-9495-0c4623cef07c.png)
