### ISSUE TITLE
Add Scope to Foodbank Text to allow active/inactive

### ISSUE THREAD

**Issue by davidpickering** [midohiofoodbank/freshtrak-pantry-finder-api#54]
The Foodbank Text Model should include a scope for 'active' where status_id = 1. Effectively, this make an on/off switch for this kind of data.

Model: https://github.com/midohiofoodbank/freshtrak-pantry-finder-api/blob/master/app/models/foodbank_text.rb

Example of Model with correct scope: https://github.com/midohiofoodbank/freshtrak-pantry-finder-api/blob/master/app/models/event_slot.rb#L10

Desired effect on the front end:
Current State:
![image](https://user-images.githubusercontent.com/11682225/90688523-94c3da80-e23c-11ea-8465-3897e10530b7.png)

Future State:
![image](https://user-images.githubusercontent.com/11682225/90688758-ea988280-e23c-11ea-9dfe-b142e1bdf962.png)

**Comment by davidpickering** [comment]
Hey @PhilNorman2 would you mind taking this on?

**Comment by PhilNorman2** [comment]
Sure.  I should have caught that in the review.

**Comment by davidpickering** [comment]
> 
> 
> Sure. I should have caught that in the review.

No worries, thanks Phil!
